print("Monkey is dancing")
print("Monkey is dancing")
print("Monkey1 is dancing")
print("Monkey1 is dancing")
print("Monkey1 is dancing")
print("Monkey1 is dancing")
print("Donkey is dancing")
print("Donkey is dancing")
